version: 1
dataset_version: db-lidarseg-v0.1
train:
- 02b4321d-9cb4-4668-a770-7fe1fdf948b0/0
- 031249ca-afd8-46f3-b8d4-923170eaa078/0
- f0471c74-fd82-4b63-a4eb-0244751aaade/0
- 0b9868d4-dda6-470c-b969-39865db1e4c3/0
- 0bee9554-81d7-4180-960b-fa0b5404c0c1/0
- 0cd437db-49aa-4721-bfc6-ff9a64cd720b/0
- 0d26c034-9c0c-49bb-90b7-9f671564e13d/0
- 0d5ec049-aa73-4eae-b3b2-a02d33d9eb14/0
- 0d7a4d86-53ca-4675-b6e4-9bdc9e405f1f/0
- 10a7da39-7412-4a03-a122-5d93fd2c0449/0
- 118075e1-7f4b-47fb-8a15-27d6f94189b0/0
- 1308a685-7e71-4559-92b9-e5ac1136ae86/0
- 13cb0a46-83b2-4e86-8cce-206ac125c6d5/0
- 179da520-f107-4466-a1b8-9b718a7825c8/0
- 18c661a6-669e-42ef-b38d-e9072420fdc1/0
- 1b297bdb-224c-48b9-9377-9de7427c67c1/0
- 1d8366ea-ff27-422c-bb9f-a55a9bbda864/0
- 1e83badc-b638-4c5b-acb5-5b0958ff9fe2/0
- 1e8cd62c-335f-461b-a546-e332f4fdf71b/0
- 1f560fd9-fa45-4509-a1a6-03fa578752b4/0
- 25a326af-347d-4100-8892-cb70e149e833/0
- 27456ad1-cbe8-481e-983f-d66f2711db91/0
- 2bf8f4ad-c0ee-456a-b236-34d77b7dcc2b/0
- 302c8ec7-c643-4aba-b7b9-053b8d4e1419/0
- 31262690-106a-419c-a71a-88eab5f163b6/0
- 3271b9f1-d8ed-4ee4-a11f-87a53e260325/0
- 329a8f81-93a5-442c-9a65-777e3fd1d8c0/0
- 35d41815-e143-45d1-b416-0d64e5be7674/0
- 3af6b0c6-ba6e-4258-b963-ab1457d7b2c1/0
- 3bc2ab13-5868-4080-a897-55f10c3f5cd8/0
- 3ce9fc98-56b9-4972-9c6f-1a85fd0241d1/0
- 3dd3db09-cc54-4b1a-aa5f-5fd8a513b4d9/0
- 3f7ea3df-f1a3-47e6-a842-7180348a1036/0
- 403043d0-917b-4bf0-a2bd-fa7b26dc5bf3/0
- 47f15bf9-14ce-48bc-a6ef-53ea49bd2804/0
- 4b09f208-623c-4383-8113-18e5123304e4/0
- 4d03c48b-f9fe-4d67-a477-b338ec07063c/0
- 4df15d41-00ae-44e2-9c11-2fc3009b0e95/0
- 4dfc2148-98cf-4daa-ae56-76abcaa8f583/0
- 4e03ea0e-0db9-418d-918f-6d124958305d/0
- 4f511b1c-deaf-4b1c-aece-bac91e3bb31b/0
- 7da88f42-bf25-4f5a-acd6-8ff547f15258/0
- e3752403-286b-4e48-a396-52d37a98054f/0
- 50debc8a-88a3-421c-a70d-25ec1a202fc0/0
- 52a1c6c9-27e9-411e-989d-a5185f00c1e9/0
- 53339877-cd51-428e-baab-0429c568ef58/0
- 55aacfc9-7b0e-4be7-9a69-c8af9fc3ea59/0
- 5c0be735-54ec-4a08-a880-6151f326c9e7/0
- 5c6e90b7-bc40-4e3c-b134-a8faa9ef919a/0
- 5ca2b34b-7e17-415a-adb2-e7d11abf3d26/0
- 5faa9f0c-e6cc-4d8d-b756-03c19b785afe/0
- 67272768-c98e-42ff-aa17-3e2161ad441e/0
- 68e1783c-d030-4031-bb63-7f9aa4b0c750/0
- 691025a5-5830-4159-ba94-4236392d967f/0
- 696a72e4-e61a-4664-bc3f-20471aff9e36/0
- 69cf54ec-7db1-44c5-a1b4-03ec14ae24fd/0
- 6a774297-0678-4f98-9b34-814ac8eab3df/0
- 6dd95e8c-f644-479f-95c6-4f3c4be910cc/0
- 6e98e46a-1194-4022-9dbf-ee8009be3945/0
- a2f32c3d-8f0d-42d2-880b-eaaa1a233102/0
- 72d64206-3288-4388-bbf0-fa4c2bfcee26/0
- 7490f24c-ce96-4f13-ac4c-29b8fd99ddd9/0
- 78ba54e0-ba3f-4210-8dd3-2340c83dfde0/0
- 7c82e145-7528-4d2e-b9a0-d022632f36a0/0
- 7ebc4c72-dc79-483b-af47-981df93dcd91/0
- 7fb53978-5c24-4d66-8948-3b8d474576dc/0
- 82066acf-5ab8-4e4e-b6de-2403da8403b2/0
- 830f6426-4c9b-495f-85f6-1a0ecbf398c9/0
- 481a9b2c-5875-4797-a90f-363daee476b2/0
- 85049cac-a473-4d3b-9bc5-f0c3a4622b19/0
- 87d6b59b-3af7-4cff-876e-f74984fc288f/0
- 8a4b050c-8689-4e85-ae53-da4e6c043208/0
- 8b568300-1999-4350-9c14-6b2bb962200b/0
- 8ed0ce56-2ed0-4788-bb8e-f9d9d98386fa/0
- 5517d0f2-23b7-4318-96fb-4c655f2cf050/0
- 91d17ccf-badf-4455-81ff-e5ad18560e96/0
- 9559074a-31ea-4666-86eb-a496999cf27c/0
- 9626fcf1-70dc-469f-9847-f437a7b669b0/0
- 99eec06a-8af4-4a09-9d07-25511eb916be/0
- 9d35f93b-fce9-44fc-8db3-6a4fc6d048b3/0
- 9f083fd3-739c-4689-a6bf-b287c7330656/0
- 9fdc38c9-431f-45d2-ab79-25bc1c0e536c/0
- a0fc9ab4-75fe-45e0-b273-9f8ca72d698c/0
- a20d5774-0f6b-4447-9f10-2225c369f6cf/0
- a261f215-6813-4cc9-aaec-0b564ed408f3/0
- a2ec45fd-c642-409b-8490-6255d7c75f61/0
- a3182ef3-1799-4f03-a26f-9c55c5215462/0
- a47f053d-0058-48e5-8ab3-a469bf683c11/0
- a521dd93-6285-4b6a-9873-d23f2f9cd50e/0
- a569acd9-f6cf-4856-bdde-7fb5dc5790fc/0
- a707d1ce-83bd-4579-87a9-50e359cbb9fa/0
- ab37d080-e0ac-42bd-96be-5039f398b161/0
- ae9b7098-2e36-4126-bd88-e51db603ce7d/0
- af2f4afe-5d8a-4167-ba6c-7494ef7b2d32/0
- b54074de-8cb1-4dfe-92c5-c13090eb0cc1/0
- ba215e3d-2bfc-4572-bf6c-870eaa3f5a46/0
- 1cca6c73-9f6e-449b-9111-4b299d816e7c/0
- c4c61a9b-bd8d-4d38-8844-1fd247d43f96/0
- c562228d-03d3-454f-a1b7-dc8659c2daad/0
- ce86a6b1-4a65-4083-8f7d-5656e1d4bbbf/0
- 7aa8888b-172d-4803-94ee-2602d95d4611/0
- d07057f1-7c61-4133-92d3-e552aa582c76/0
- d1a36517-4c2f-456b-92d2-2193d5b6f0d0/0
- d1ae0843-89bf-4273-a2f8-4a4680703f4f/0
- d5eaac2e-697a-42f5-b646-561a502a2b29/0
- d69408ec-abb5-4e21-a380-e53231dbb198/0
- d6f77c9b-5280-495c-90dd-d093b8b1c707/0
- d93640d9-26ec-42a4-abcd-34f36e23c8c0/0
- da0c9783-0b2e-4b18-9643-015db895f27d/0
- a4905914-822c-4684-9dba-bc62e5b597df/0
- dd5e8b6d-41cb-4b47-971a-f3c9bf054285/0
- de6fa37f-90c6-480e-a527-e6e290b50fd0/0
- e64ab39d-7741-4723-b4e2-778805c8cd95/0
- e7670827-8a73-494c-8d0c-5eb853a2e82c/0
- e875e429-9555-4c13-9208-41ea48cfab95/0
- e8e9f4cb-f288-43dd-bb30-409cdfa9be3e/0
- e982c083-67db-42d5-8f3e-8816c56c1410/0
- ecc49ea9-1304-4849-b43a-8895dd1f4820/0
- ecfd76f9-a02b-4797-b942-424f61b36277/0
- e08d24c1-72ff-426a-98bd-fb9a8b8821d7/0
- f0f6a201-57bf-43ac-b3eb-83fec0c647d3/0
- f7043ff4-d5e6-4f0a-ac1c-ca236cbe9b18/0
- f763ac95-578a-4b07-893b-d6f4fd4f220e/0
- ffc0bf1d-80a8-4882-87e2-fd2854c772aa/0
val:
- 03a65c3f-b720-4156-b31e-1d7ba2cda51e/0
- 0872d5b1-5d30-4832-8589-6ba9d06f924d/0
- 0c3204b1-af6e-496a-ba8c-4e6ae9360cb7/0
- 0df5981c-71c5-410e-b988-e803f40c3062/0
- dc66def7-f83d-4541-927a-61b85943fec3/0
- 15b034c7-a819-4e1b-8a28-30a63e2d9179/0
- 1974e4db-79a9-4c9b-9e69-d27fc201e09b/0
- 1e15c5ee-cf7d-4c6f-bb00-f43e42260132/0
- 200a1b95-a79e-4b29-97e2-4a15b03286f3/0
- 24d6f3f3-2efb-4874-bcc6-7e1c67bb84d9/0
- 3538b2bf-09fb-4c76-b20a-6f57cf4a7f13/0
- 357db75b-5b94-4f8d-bc7b-1bf4054865f2/0
- 3c822e99-b3b7-4623-82c7-16ec49010f4f/0
- 3d440cc9-c853-4f7a-9365-bd9ab1954649/0
- 41feeaae-0763-4f91-9ff4-c2c756a1eb5e/0
- 46230989-9107-4a48-b34d-d2c603c349eb/0
- 4ac937f0-e255-4c5a-9771-045060d018db/0
- 50a3ead3-14f3-471f-aed1-41392be1c9b1/0
- 5e615144-ec92-425c-a3fb-7e846f14c4e9/0
- 66b8f2cc-8ddf-4039-9b06-f213371df999/0
- 683c630d-2e60-40c5-bd33-d12e17dead39/0
- 7773296a-8546-41a5-bba0-903d46fe3395/0
- 7a6126c6-aab3-4ad9-b816-811085cf2a6e/0
- 88df1de6-ade0-40a7-8013-5d8d796c138e/0
- 8cc01682-ccc9-4f8e-9a83-3107c37bfd2c/0
- 93ff703a-1905-478d-a9a0-2a0fc9949601/0
- a280b07b-7265-4f0d-89ec-11ccfba54a9b/0
- a3e7e8ea-8803-4d7c-8ee9-84af02409444/0
- f33a23a7-dafb-4d09-aeac-d70dcf13848c/0
- b6b9684e-36fd-490b-b875-63ed59278b4a/0
- e3d51ef9-8f5a-468a-858e-1fc49fe0fe81/0
- c81aafca-80b0-4beb-9ed1-74860a5a3b30/0
- e37f7385-a2da-49e2-af26-03deac9faf1a/0
- e8cf9c74-40e8-46ee-9db4-1dda3204272e/0
- f87943c5-6cf2-4cf0-a1cc-5fa79d92b61a/0
- fc51ba5f-f12e-4d28-8ba0-3e8711c83ea4/0
test:
- 0a070e35-78ab-4b31-8757-29978f5c040d/0
- 0d3f4f8c-b0cf-4f94-8557-cc0909959046/0
- 10e2fe62-990d-4faf-aa5d-9ecd57cbf8de/0
- 12db8b76-3ea4-4dd3-be6d-71f346a79e8d/0
- 15cb5202-ffaa-42dc-9bf3-fe665419e386/0
- 34a34d01-47d3-4071-9052-b88ae6f8ac1b/0
- 4b026239-f58a-4c12-b728-5b8ecfc71eeb/0
- 55689080-dc97-45fc-958c-44a9d82e09df/0
- 5c87ca7b-e163-432a-a934-6a4c08694fe9/0
- 625ec441-77e5-489b-a336-29796e6481ff/0
- 6637295f-c3e1-40dc-afae-0ff6d4da7b15/0
- 7b5d3d51-bf9d-411c-8a0b-3761b921c4a1/0
- 7caa9270-9380-4714-916b-a232f87268d5/0
- 89683927-75d1-4c38-8d69-03176ffe02cf/0
- 97640a4d-3c33-4879-9f7e-9760ac3ea118/0
- cf7c302a-d383-4d82-840a-a5d673cee910/0
- e70449bb-17bc-4623-88f8-9f2864bf02e6/0
- ec03a832-017a-43c8-8bc1-1a10b12eaa90/0
